### ISSUE TITLE
figma design for AI age range

### ISSUE THREAD

**Issue by TalebRafiepour** [TalaoDAO/AltMe#1002]

**Comment by hawkbee1** [comment]
currently not handling errors from YOTI API


![Image](https://user-images.githubusercontent.com/49282360/201680062-7e3e0969-377a-470f-ad98-e4f4b76fbc6c.png)

**Comment by hawkbee1** [comment]
I suppose that's link to ML, there is a flow of this error before taking picture.

```
 PlatformException(error, Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format., null, java.lang.IllegalArgumentException: Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format.
      	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:2)
      	at com.google.mlkit.vision.common.InputImage.<init>(com.google.mlkit:vision-common@@17.1.0:8)
      	at com.google.mlkit.vision.common.InputImage.fromByteArray(com.google.mlkit:vision-common@@17.1.0:2)
      	at com.google_mlkit_commons.InputImageConverter.getInputImageFromData(InputImageConverter.java:36)
      	at com.google_mlkit_face_detection.FaceDetector.handleDetection(FaceDetector.java:55)
      	at com.google_mlkit_face_detection.FaceDetector.onMethodCall(FaceDetector.java:41)
      	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
      	at android.os.Handler.handleCallback(Handler.java:942)
      	at android.os.Handler.dispatchMessage(Handler.java:99)
      	at android.os.Looper.loopOnce(Looper.java:201)
      	at android.os.Looper.loop(Looper.java:288)
      	at android.app.ActivityThread.main(ActivityThread.java:7898)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
      )

[log] #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
        <asynchronous suspension>
#2      MethodChannel.invokeListMethod
package:flutter/…/services/platform_channel.dart:485
        <asynchronous suspension>
#3      FaceDetector.processImage
package:google_mlkit_face_detection/src/face_detector.dart:22
        <asynchronous suspension>
```



![Image](https://user-images.githubusercontent.com/49282360/201683811-3fb4ad93-20c9-4740-99a0-52a26cc38b53.png)

**Comment by hawkbee1** [comment]
Issue when sending picture


![Image](https://user-images.githubusercontent.com/49282360/201684420-dc0896bc-dfd0-4639-81e0-cfcb1293b2b4.png)

**Comment by ThierryThevenet** [comment]
we need to get AI working as soon as possible
