### ISSUE TITLE
Pixel 6: issue with flutter secure storage package

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1591]
```
PlatformException(Exception encountered, readAll, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
	at b8.h.b(StorageCipher18Implementation.java:8)
	at a8.a.c(FlutterSecureStorage.java:2)
	at a8.a.l(FlutterSecureStorage.java:11)
	at a8.e$b.run(FlutterSecureStoragePlugin.java:13)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null)
```

```
Occurred in non-app: <asynchronous suspension>
System
credential_repository.dart in CredentialsRepository.findAll at line 30 within altme
In App
Called from: <asynchronous suspension>
System
credentials_cubit.dart in CredentialsCubit.loadAllCredentials at line 56 within altme
In App
Called from: <asynchronous suspension>
System
is_wallet_created.dart in isWalletCreated at line 77 within altme
In App
Called from: <asynchronous suspension>
System
splash_cubit.dart in SplashCubit.initialiseApp.<fn> at line 44 within altme
```

Known issue: https://github.com/mogol/flutter_secure_storage/issues/354

**Comment by bibash28** [comment]
@hawkbee1 I have enabled encryptedSharedPreferences for android. Please test in [secure_storage_android_fix](https://github.com/TalaoDAO/AltMe/compare/secure_storage_android_fix)

**Comment by hawkbee1** [comment]
@hawkbee1 test on android
