### ISSUE TITLE
beacon issue on android during onboarding

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/AltMe#1641]
E/AndroidRuntime(31923): FATAL EXCEPTION: DefaultDispatcher-worker-3
E/AndroidRuntime(31923): Process: co.altme.alt.me.altme, PID: 31923
E/AndroidRuntime(31923): com.google.crypto.tink.shaded.protobuf.c0: Protocol message contained an invalid tag (zero).
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.e.G(ArrayDecoders.java:4)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.v0.d0(MessageSchema.java:56)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.v0.b(MessageSchema.java:2)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.e.p(ArrayDecoders.java:5)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.e.q(ArrayDecoders.java:1)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.v0.d0(MessageSchema.java:51)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.v0.b(MessageSchema.java:2)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.z.J(GeneratedMessageLite.java:3)
E/AndroidRuntime(31923): 	at com.google.crypto.tink.shaded.protobuf.z.G(GeneratedMessageLite.java:2)
E/AndroidRuntime(31923): 	at t3.i0.W(Unknown Source:2)
E/AndroidRuntime(31923): 	at n3.d.read(Unknown Source:8)
E/AndroidRuntime(31923): 	at g3.c.a(Unknown Source:0)
E/AndroidRuntime(31923): 	at n3.a$b.e(AndroidKeysetManager.java:4)
E/AndroidRuntime(31923): 	at n3.a$b.f(AndroidKeysetManager.java:1)
E/AndroidRuntime(31923): 	at n3.a$b.d(AndroidKeysetManager.java:3)
E/AndroidRuntime(31923): 	at androidx.security.crypto.a$a.a(EncryptedFile.java:7)
E/AndroidRuntime(31923): 	at it.airgap.beaconsdk.core.internal.storage.sharedpreferences.encryptedfile.TargetEncryptedFileManager$write$2$1.invokeSuspend(TargetEncryptedFileManager.kt:8)
E/AndroidRuntime(31923): 	at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:4)
E/AndroidRuntime(31923): 	at kotlinx.coroutines.d1.run(DispatchedTask.kt:18)
E/AndroidRuntime(31923): 	at kotlinx.coroutines.internal.m.run(LimitedDispatcher.kt:2)
E/AndroidRuntime(31923): 	at kotlinx.coroutines.scheduling.k.run(Tasks.kt:1)
E/AndroidRuntime(31923): 	at kotlinx.coroutines.scheduling.a.r(CoroutineScheduler.kt:1)
E/AndroidRuntime(31923): 	at kotlinx.coroutines.scheduling.a$c.d(CoroutineScheduler.kt:4)
E/AndroidRuntime(31923): 	at kotlinx.coroutines.scheduling.a$c.n(CoroutineScheduler.kt:4)
E/AndroidRuntime(31923): 	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
E/AndroidRuntime(31923): 	Suppressed: kotlinx.coroutines.b1: [v2{Cancelling}@25b2f9b, Dispatchers.IO]

**Comment by hawkbee1** [comment]
Only on certain android devices (Pixel 6 and @HugoNDO's motorola phone).
Issue is opened in air gap repository. 
https://github.com/airgap-it/beacon-android-sdk/issues/15
